name: Scrape latest data

on:
  push:
  workflow_dispatch:
#   schedule:
#     - cron: '16,36,56 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        curl --request POST --url https://searx.xyz --form 'q=Florian Plattner' --form format=json | jq . > results.json
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
